### ISSUE TITLE
No menu to create table

### ISSUE THREAD

**Issue by JointVentureJones** [editor-js/table#121]
I´m using the latest version. I have no menu to create a table, i only can paste a table into the editor. Is there any way to get a menu working. I tried it with
```
var editor = EditorJS({
  tools: {
    table: {
      class: Table,
      inlineToolbar: true,
      config: {
        rows: 2,
        cols: 3,
      },
    },
  },
});
```

**Comment by neSpecc** [comment]
The Table tool has its own icons and it should be displayed in the Toolbox. I can't reproduce your problem. Provide steps to reproduce or working demo

**Comment by neSpecc** [comment]
Ok, no problem
