### ISSUE TITLE
block-changed events are fired even without changes

### ISSUE THREAD

**Issue by notaloop0000** [editor-js/table#125]
Reproduction: click on a table, move the mouse around, click mouse on other cells.

My service relies on `block-changed `event to save changes from the editor, and unwanted events like this cause unnecessary saving requests. Could someone suggest a solution until we having a fix?

**Comment by adas1a** [comment]
Bump
I have the same issue, hovering on table causes an onChange event to be fired

**Comment by morsecoding** [comment]
Same issue here. The excessive calls makes it impossible to know when a true change actually occurs.

**Comment by gvanbeck** [comment]
+1
