### ISSUE TITLE
Type signatures causing errors in build process

### ISSUE THREAD

**Issue by BernhardBehrendt** [editor-js/table#155]
Since I've made dependency updates im facing errors caused by type definition file.

Installed version(s):

````
    "@editorjs/checklist": "^1.6.0",
    "@editorjs/code": "^2.9.0",
    "@editorjs/editorjs": "^2.30.5",
    "@editorjs/header": "^2.8.7",
    "@editorjs/list": "^1.10.0",
    "@editorjs/marker": "^1.4.0",
    "@editorjs/quote": "^2.7.2",
    "@editorjs/table": "^2.4.1",
    "editorjs-tooltip": "^1.2.2",
````

<img width="699" alt="sc" src="https://github.com/user-attachments/assets/620ed746-1943-41e6-af3f-e8c596c80639">

This line within the file `node_modules/@editorjs/table/dist/toolbox.d.ts:29:38` causing the error: 

<img width="671" alt="Bildschirmfoto 2024-08-28 um 23 10 53" src="https://github.com/user-attachments/assets/23c10500-e4a4-49ab-a480-d2b429c6df4e">

and modifying it like this solved it.

<img width="556" alt="Bildschirmfoto 2024-08-28 um 23 11 12" src="https://github.com/user-attachments/assets/73f2e775-007c-415f-ae10-d1168e7e6a6d">

**Comment by btroncone** [comment]
I'm having the same issue, build fails with:

```
node_modules/@editorjs/table/dist/toolbox.d.ts:29:48 - error TS2339: Property 'cssModifier' does not exist on type '{}'.

29     constructor({ api, items, onOpen, onClose, cssModifier }: object);```

Please advise, thanks!

**Comment by Sozialarchiv** [comment]
I will have look into the issue.

As a temporary workaround you can set skipLibCheck to true in you tsconfig.json
