### ISSUE TITLE
How to remove rows/colums from table?

### ISSUE THREAD

**Issue by talyguryn** [editor-js/table#30]

**Comment by thylsky** [comment]
Any progress on this @gohabereg @horoyami? Also it would be nice to have possibility to add table header tag.

**Comment by adrienne** [comment]
Definitely need to be able to remove rows, and also set a header row.

**Comment by calumk** [comment]
I have made a proposal for this feature.
#48

**Comment by rmdwirizki** [comment]
someone made this https://github.com/groupher/editor-table, maybe can be used as reference 
![image](https://user-images.githubusercontent.com/13674295/81890752-ea9b3d80-95d0-11ea-95ea-f2a7167ee929.png)

**Comment by abby-d** [comment]
This would be awesome to have. Any update on this?

**Comment by JimishF** [comment]
Any updates?

**Comment by simpleauthority** [comment]
Is there actually no way to do this right now? o.O

**Comment by StarAzure** [comment]
The lines are so sensitive and if you accidently click the bottom of a line, a new row gets added. Then you cannot remove a row and delete the entire table to fix this. Not so great so had to remove this plugin.

**Comment by simpleauthority** [comment]
> The lines are so sensitive and if you accidently click the bottom of a line, a new row gets added. Then you cannot remove a row and delete the entire table to fix this. Not so great so had to remove this plugin.

I agree. This plugin is useless w/o ability to remove rows. However, somebody made a fork that adds the functionality and it works well. https://github.com/editor-js/table/pull/48#issuecomment-646722158

**Comment by StarAzure** [comment]
> > The lines are so sensitive and if you accidently click the bottom of a line, a new row gets added. Then you cannot remove a row and delete the entire table to fix this. Not so great so had to remove this plugin.
> 
> I agree. This plugin is useless w/o ability to remove rows. However, somebody made a fork that adds the functionality and it works well. [#48 (comment)](https://github.com/editor-js/table/pull/48#issuecomment-646722158)
> 
> All you have to do is replace the table dependency and reinstall deps: [#48 (comment)](https://github.com/editor-js/table/pull/48#issuecomment-665458593)

Thanks. That one seems to have a bug when clicking the line at times - `TypeError: Cannot read property 'button' of null`

**Comment by simpleauthority** [comment]
> > > The lines are so sensitive and if you accidently click the bottom of a line, a new row gets added. Then you cannot remove a row and delete the entire table to fix this. Not so great so had to remove this plugin.
> > 
> > 
> > I agree. This plugin is useless w/o ability to remove rows. However, somebody made a fork that adds the functionality and it works well. [#48 (comment)](https://github.com/editor-js/table/pull/48#issuecomment-646722158)
> > All you have to do is replace the table dependency and reinstall deps: [#48 (comment)](https://github.com/editor-js/table/pull/48#issuecomment-665458593)
> 
> Thanks. That one seems to have a bug when clicking the line at times - `TypeError: Cannot read property 'button' of null`

Yeah I think it is implemented kind of janky, author admitted as such. But it's what we've got as editorjs team doesn't seem to care about this feature. Meh.

**Comment by oknoorap** [comment]
The team closes my issue #698, I think they will not planned to add remove row/column in the near feature.

**Comment by simpleauthority** [comment]
> The team closes my issue [#698](https://github.com/codex-team/editor.js/issues/698), I think they will not planned to add remove row/column in the near feature.

Yes, for whatever reason they don't care. Looks very bad.

**Comment by christoph-kluge** [comment]
Another proposal of this feature (based on @calumk version) is here:

#61

**Comment by JoNMii** [comment]
> The team closes my issue [#698](https://github.com/codex-team/editor.js/issues/698), I think they will not planned to add remove row/column in the near future.

Thanks for sharing it. I was started using EditorJS but i think im gonna leave it. Looks promising but its unfinished somehow.

**Comment by SinrVolcano** [comment]
> > The team closes my issue [#698](https://github.com/codex-team/editor.js/issues/698), I think they will not planned to add remove row/column in the near future.
> 
> Thanks for sharing it. I was started using EditorJS but i think im gonna leave it. Looks promising but its unfinished somehow.

What library can I get to replace the editorjs?

**Comment by johnpuddephatt** [comment]
I've been using this alternative table plugin and have been happy with it so far: https://github.com/codinova-tech/editorjs-table 

row/column management is done through the tuning menu which I find works well.

**Comment by Awanys** [comment]
Yeah, it's totally in need. :(

**Comment by neSpecc** [comment]
Thanks to all.

The new Table tool is here. You'll be able to remove all those extra columns at last.

Resolved by #67
