### ISSUE TITLE
Strange behaviour while adding new elements

### ISSUE THREAD

**Issue by talyguryn** [editor-js/table#31]
![jan-08-2019 20-28-15](https://user-images.githubusercontent.com/15259299/50848233-bed8c980-1384-11e9-8015-2745fcd54b40.gif)

**Comment by Benjaminryejones** [comment]
+1 - I have the same behavior adding rows as well (ie, clicking the bottom plus sign adds a row on top)

**Comment by neSpecc** [comment]
Resolved by #67
