### ISSUE TITLE
Delete cells

### ISSUE THREAD

**Issue by jjzcru** [editor-js/table#33]
There is an option to delete and remove cells in the table?

**Comment by Eggwise** [comment]
This would be nice...

**Comment by Awilum** [comment]
is it possible to delete rows and cells ?

**Comment by fcontreras2** [comment]
i have the same problem. It's a great plugin but it's neccesary this functionality

**Comment by jgui1129** [comment]
Voting for this feature.

**Comment by rajulapudi** [comment]
A required feature

**Comment by leorolland** [comment]
Where could we nicely add a button that destroys column or line ?

**Comment by romansidorov** [comment]
> Where could we nicely add a button that destroys column or line ?

I guess the best way to place deleting controls is there:
![Screenshot 2020-02-07 at 12 51 08](https://user-images.githubusercontent.com/22329890/74019371-8ef55e80-49a8-11ea-8d56-2c9d1e3d2c0f.png)

It's clear and accords to a placement of controls for adding rows and cols.

**Comment by hariria** [comment]
I would do it like dropbox paper tables where they have a skinny row above the columns and a skinny column to the left of the rows and you can select rows you want to delete

**Comment by calumk** [comment]
I have made a proposal for this feature.
 #48

**Comment by Davidzhu001** [comment]
any solutions for this request?

**Comment by Davidzhu001** [comment]
please add this function. i saw some merge request have the solution.

**Comment by christoph-kluge** [comment]
Another proposal of this feature (based on @calumk version) is here:

#61

**Comment by Awilum** [comment]
any updates or estimates for this?

**Comment by calumk** [comment]
@Awilum - See : https://github.com/editor-js/table/pull/61

**Comment by Awilum** [comment]
> @Awilum - See : #61

But it is not merged yet ?

**Comment by calumk** [comment]
And #61 explains why, the Devs have decided not to support this, so it never will.

**Comment by neSpecc** [comment]
Resolved by #67
