### ISSUE TITLE
Shift + Enter aka Linebreak does not work

### ISSUE THREAD

**Issue by christoph-kluge** [editor-js/table#36]
Shit + Enter does work in paragraphs (and other tools) but it does not for the Table-Tool. 

Does someone got a hint for me? I didn't found the class / function where the html is inserted from the toolbar. Everything else from the toolbar seems work w/o a problem:

<img width="984" alt="Screen Shot 2019-09-24 at 19 40 18" src="https://user-images.githubusercontent.com/1446269/65538450-a3f4b800-df07-11e9-8c9d-347638d541f3.png">

Row 3 - Cell 2 does not work.  When save() is executed it saves: 

`Row 3 - Cell 2 - Line 1Row 3 - Cell 2 - Line2` instead of:
`Row 3 - Cell 2 - Line 1<br>Row 3 - Cell 2 - Line2`

Either a `<br>` or a `\n` is missing. Whereas inside a paragraph it converts automatically to `<br>`. 

I'm up for hints and also willing to contribute 👍

**Comment by neSpecc** [comment]
Resolved by #67

**Comment by RyoYamashiro** [comment]
has anyone solved this problem?

**Comment by mannv** [comment]
```
table: {
  class: Table,
  inlineToolbar: true
}
```
**=> break line not work** Please fix 

```
table: {
  class: Table,
  inlineToolbar: false
}
```
**=> break line work**
