### ISSUE TITLE
Feature Request: Paste table

### ISSUE THREAD

**Issue by douglasmiranda** [editor-js/table#38]
It would be nice if we'd be able to paste tables from spreadsheets/web to the editor.

**Comment by douglasmiranda** [comment]
codex-team/editor.js/issues/729

**Comment by cgvictor** [comment]
> [codex-team/editor.js/issues/729](https://github.com/codex-team/editor.js/issues/729)

Sorry, that's interesting discussion, but seems slightly irrelevant. 
It's not about "how we preserve styles", but just "how to translate table structure from clipboard to block data". 
And the example code could be seen here: https://github.com/editor-js/table/issues/78#issuecomment-1031581164 (= iterate over tr/tds and create corresponding structure).

Hope to something like that in editor-js bundled somewhen.
