### ISSUE TITLE
Table rows and columns are trimmed back to config values on reopening

### ISSUE THREAD

**Issue by bitfactory-nathan-waelkens** [editor-js/table#41]
Version: 1.2.0

**Problem**
I can create a table, table is stored successfully. When I edit the table, the number of rows and columns visible is the number of default configured visible rows or columns. 

**Reproduce**
1. Configure table for example like this: 
...
`table: {
      class: Table,
      inlineToolbar: true,
      config: {
        rows: 2,
        cols: 2
      }
    },`
...

2. Create and store a table with 3 rows and columns. Verify it is stored successfully by checking your database - or whatever persistence you use.

3. Open the table again in the editor. The table will be trimmed back to 2 rows and columns, loosing data on update. 

**Quickfix if someone runs into this problem**
Just remove `config:{rows:2, cols: 2}` completely and it works just fine!

**Comment by next-direction** [comment]
Just encountered the same issue. I Initialized it with { rows: 1, cols: 1 } because deleting rows is not possible, so I wanted to start with as little cells as possible.

On edit I had only one cell left of six.
