### ISSUE TITLE
Module not found: Can't resolve '@editorjs/table'

### ISSUE THREAD

**Issue by fkocovski** [editor-js/table#74]
This happens since version 2.0.0.

Shouldn't files inside the `dist` folder be named `bundle.js`?

![Screenshot 2021-07-23 at 09 27 34](https://user-images.githubusercontent.com/9000611/126750151-64caf82a-dcc7-4622-98a9-8ad3e30ec278.png)

**Comment by talyguryn** [comment]
sorry. fix will be deployed in minutes

**Comment by fkocovski** [comment]
Thank you, however I tried with 2.0.1 but still the same problem. In `node_modules` it still appears as `table.js`

**Comment by fkocovski** [comment]
Ok my bad I had to restart the dev server. It now appears to be working :)
