### ISSUE TITLE
Bug: Cannot read properties of null (reading 'getBoundingClientRect') on row delete

### ISSUE THREAD

**Issue by sethmichaelbrown** [editor-js/table#79]
### Issue - 
When deleting a row of the table, the following error is thrown
```
table.js:1 Uncaught TypeError: Cannot read properties of null (reading 'getBoundingClientRect')
    at l (table.js:1)
    at c (table.js:1)
    at table.js:1
    at u.show (table.js:1)
    at k.updateToolboxesPosition (table.js:1)
    at k.hideToolboxes (table.js:1)
    at Object.onClick (table.js:1)
    at popoverClicked (table.js:1)
    at HTMLDivElement.<anonymous> (table.js:1)
```
This is not currently breaking the UI, but I believe this should be addressed.

### Environment -
@editorjs/table - v2.0.1
@editorjs/editorjs - v2.22.2
react - v16.9.0
@storybook/react - v6.3.10

### Steps to Reproduce

- Create an EditorJS instance with a table
- Open console
- Add row to the table
- Delete row that was just added
- Expect to see error thrown

 ### Screen Recording

https://user-images.githubusercontent.com/40705253/138748720-86c3c36e-833e-4640-829e-b4b0729b2ae0.mov

### Potential Solution
Depending on what is being measures, a potential fix for this might be adding optional chaining to the function call. Something like `elementToBeMeasured?.getBoundingClientRec() ?? {} // defaults to {} if elementToBeMeasured does not exist`

**Comment by Yurgeman** [comment]
similar problem 
`@editorjs/table: 2.0.1` & `@editorjs/editorjs: 2.22.2`

**Comment by charles01pd2018** [comment]
I copied @orionmiz PR and created a new npm module that gets rid of this bug since it looks like this is still an issue:
https://www.npmjs.com/package/@pofo/editorjs-table
