### ISSUE TITLE
Added number of cells is not correct when adding new row

### ISSUE THREAD

**Issue by Frank-Mayer** [editor-js/table#85]
Added number of cells is not correct. By adding a new row, there is always added one cell more than it should be.

After initialization:
<img width="420" alt="Bildschirmfoto 2021-12-11 um 23 38 34" src="https://user-images.githubusercontent.com/53651857/145693749-06ec9660-bf6d-48e4-a805-9ebeb114032b.png">

Added rows:
<img width="420" alt="Bildschirmfoto 2021-12-11 um 23 39 01" src="https://user-images.githubusercontent.com/53651857/145693759-9b264230-623f-4df3-bee9-6d9a6b1f4a23.png">

Chrome on Mac

Editor.js 2.22.2 from npm
Parcel 2.0.1

**Comment by samy-mnasri** [comment]
+1

**Comment by medzhidov** [comment]
This because of your browser extensions that adds elements to contenteditable elements. Just now meet this problem and solved it by turning off Language Tool in browser

**Comment by Frank-Mayer** [comment]
As a user of a editor-js website I wouldn't continue using the website if i had to turn off language tool.

I use an extension like this because I need it.

Would be nice to use both great tools together.

**Comment by Mortimer333** [comment]
+1
